version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.0
    volumes:
      # Mount configuration file
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      # PENTING: Port UDP untuk GELF yang akan didengarkan oleh Logstash
      - "12201:12201/udp" 
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  app:
    image: busybox
    # Sintaks Literal Block Scalar (|) untuk menghindari masalah spasi.
    command: |
      sh -c 'while true; do echo "{\"version\":\"1.1\", \"host\":\"app\", \"short_message\":\"App log entry: $$(date)\", \"level\":6}" | nc -u logstash 12201; sleep 2; done'
    networks:
      - elk

networks:
  elk:
    driver: bridge
